import '@/app/globals.css'
import '@assets/iconify-icons/generated-icons.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="w-full" suppressHydrationWarning>
      <body className="flex w-full min-h-screen flex-col" suppressHydrationWarning>{children}</body>
    </html>
  )
}
